version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  a-l-envers.cyrhades.fr:
    image: anssi/fcsc2022-misc-a-l-envers:latest
    ports:
      - ${PORT_SSH}:4000
